### ISSUE TITLE
Solve TODO's in Vue file

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-dashboard-2-ui-video#17]
There are 11 TODO's in the Vue [file](https://github.com/bartbutenaers/node-red-dashboard-2-ui-video/blob/main/ui/components/UIVideo.vue) which need to be investigated

- [ ] is `...mapState('data', ['messages', 'properties'])``required for this node.  I assume yes, but not sure what it does.
- [ ] should this node store all input messages, or only the ones with a payload, or no messages at all.
- [x] when the video element has loaded its metadata, the video starts playing (if autoplay has been enabled).  However when streaming Hls, the Hls.js library will already do the same.
- [ ] how to handle errors thrown by the video element itself.
- [ ] the *"presentationMode"* property is not available in my Chrome on Windows 10.  Not sure how it works and which browsers support it.  Can't find much info about it...
- [ ] the *"displayingFullscreen"* property is not available in my Chrome on Windows 10.  Not sure how it works and which browsers support it.  Can't find much info about it...
- [ ] is `null` good enough for the IntersectionObserver in the new VueJs dashboard.  In the old ui-mp4frag node the root node was something AngularJs based element from the dashboard.
- [x] should ´this.$socket?.off´ be called.  I assume yes for th widget-load event, but not for the msg event (because that is handled by the dataTracker module I assume).  I should have a look how the core nodes do it...
- [x] the assumption that all m3u8 playlists are Hls streams, is just a limitation of this node.  So I need to put that in the code and documentation.
- [x] In case of native Hls, the cleanup code should be different.
- [x] In case of Hls.js streaming, the cleanup code might need to be changed
